app:
  datasource:
    #url: jdbc:h2:file:C:/Java/h2/hello;DB_CLOSE_ON_EXIT=FALSE;AUTO_SERVER=TRUE
    url: jdbc:h2:mem:testdb
    username: sa
    password: ENC(bUs866RxLZk7jGQNHIE4AMdGR3JCQrbnoyqc0OXZVWK2wuuCqjECspyYC48LGGIJ)
    driver-class-name: org.h2.Driver
    dialect: org.hibernate.dialect.H2Dialect
  hello:
    message: Hello World!!!
    from-id: bala@xyz.com
